#!/bin/bash
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 1 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 2 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 3 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 4 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 5 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 6 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 7 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 8 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 9 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 10 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 11 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 12 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 13 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 14 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 15 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 16 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 17 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 18 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 19 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 20 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 21 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 22 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 23 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 24 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 25 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 26 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 27 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 28 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 29 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 30 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 31 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 32 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 33 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 34 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 35 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 36 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 37 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 38 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 39 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 40 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 41 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 42 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 43 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 44 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 45 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 46 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 47 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 48 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 49 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 50 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 51 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 52 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 53 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 54 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 55 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 56 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 57 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 58 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 59 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 60 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 61 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 62 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 63 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 64 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 65 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 66 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 67 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 68 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 69 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 70 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 71 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 72 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 73 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 74 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 75 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 76 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 77 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 78 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 79 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 80 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 81 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 82 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 83 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 84 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 85 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 86 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 87 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 88 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 89 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 90 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 91 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 92 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 93 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 94 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 95 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 96 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 97 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 98 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 99 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL069C --paralog2 YIL133C --sim_num 100 --heterogeneity --case JSAnalyses 
