#!/bin/bash
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 1 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 2 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 3 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 4 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 5 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 6 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 7 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 8 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 9 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 10 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 11 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 12 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 13 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 14 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 15 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 16 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 17 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 18 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 19 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 20 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 21 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 22 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 23 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 24 --heterogeneity --case JSAnalyses 
python Run_HKY_PSJS.py --paralog1 YNL301C --paralog2 YOL120C --sim_num 25 --heterogeneity --case JSAnalyses 
