#!/bin/bash
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YLR406C_YDL075W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YER131W_YGL189C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YML026C_YDR450W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YNL301C_YOL120C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YHR106W_YDR353W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YIL057C_YER067W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YPL087W_YBR183W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YNL069C_YIL133C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YDR518W_YCL043C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YGR043C_YLR354C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YPR157W_YGR141W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YDR099W_YER177W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YBR024W_YBR037C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YPL037C_YDR252W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YMR143W_YDL083C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YPR159W_YGR143W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YJL177W_YKL180W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YGL133W_YPL216W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YJR048W_YEL039C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YBR191W_YPL079W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YER074W_YIL069C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YDR418W_YEL054C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YNL049C_YIL109C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YBR117C_YPR074C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YPL232W_YMR183C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YLR284C_YOR180C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YBL087C_YER117W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YGL062W_YBR218C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YIR033W_YKL020C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YMR243C_YOR316C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YLR333C_YGR027C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YMR142C_YDL082W_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YER102W_YBL072C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YAL056W_YOR371C_One_rate_nonclock.sh  
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_HKY_YDR438W_YML018C_One_rate_nonclock.sh  
