#!/bin/bash
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_1_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_2_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_3_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_4_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_5_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_6_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_7_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_8_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_9_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_10_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_11_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_12_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_13_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_14_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_15_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_16_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_17_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_18_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_19_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_20_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_21_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_22_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_23_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_24_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_25_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_26_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_27_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_28_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_29_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_30_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_31_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_32_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_33_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_34_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_35_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_36_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_37_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_38_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_39_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_40_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_41_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_42_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_43_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_44_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_45_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_46_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_47_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_48_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_49_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_50_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_51_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_52_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_53_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_54_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_55_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_56_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_57_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_58_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_59_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_60_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_61_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_62_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_63_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_64_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_65_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_66_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_67_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_68_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_69_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_70_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_71_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_72_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_73_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_74_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_75_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_76_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_77_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_78_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_79_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_80_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_81_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_82_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_83_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_84_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_85_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_86_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_87_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_88_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_89_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_90_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_91_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_92_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_93_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_94_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_95_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_96_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_97_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_98_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_99_Tract_400.0.sh 
sbatch -o Bias-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Bias_HKY_100_Tract_400.0.sh 
