#!/bin/bash
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_1_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_2_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_3_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_4_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_5_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_6_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_7_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_8_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_9_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_10_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_11_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_12_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_13_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_14_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_15_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_16_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_17_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_18_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_19_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_20_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_21_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_22_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_23_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_24_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_25_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_26_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_27_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_28_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_29_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_30_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_31_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_32_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_33_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_34_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_35_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_36_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_37_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_38_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_39_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_40_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_41_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_42_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_43_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_44_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_45_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_46_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_47_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_48_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_49_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_50_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_51_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_52_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_53_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_54_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_55_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_56_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_57_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_58_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_59_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_60_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_61_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_62_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_63_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_64_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_65_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_66_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_67_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_68_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_69_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_70_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_71_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_72_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_73_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_74_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_75_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_76_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_77_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_78_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_79_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_80_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_81_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_82_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_83_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_84_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_85_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_86_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_87_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_88_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_89_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_90_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_91_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_92_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_93_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_94_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_95_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_96_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_97_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_98_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_99_Tract_500.0.sh 
sbatch -o Grid-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Grid_HKY_100_Tract_500.0.sh 
