---
title: "GridWeight"
author: "Xiang Ji"
date: "10/19/2017"
output: html_document
---

This file reads the log likelihood of all pairs apart same distance of the simulated datasets.

```{r, echo=FALSE}
rm(list=ls())  # clean up workspace
setwd("/Users/xji3/GitFolders/YeastIGCTract/SimulationStudy/")

Tract.list <- c(50.0)
for(tract in Tract.list){
  grid.lnL <- NULL
  for(sim in 1:100){
    grid.lnl.file <- paste("./summary/Tract_", toString(tract), '.0_HKY/sim_', 
                      toString(sim), '/PSJS_HKY_rv_sim_',
                      toString(sim), '_Tract_', tract, '.0_grid_lnL.txt', sep = "")
    grid.lnL <- read.table(grid.lnl.file)
    col.names <- strsplit(readLines(grid.lnl.file, n=1), '\t')
    colnames(grid.lnL) <- col.names[[1]]
    assign(paste("Tract_", tract, ".0_sim_", sim, "_grid_lnL", sep = ""), grid.lnL)
  }
}

guess.list <- c(50.0, 100.0, 250.0, 500.0)
# Now read in PSJS summary results 
for(tract in Tract.list){
  for(guess in guess.list){
    PSJS.tract.summary <- NULL
    for(sim in 1:100){
      
      PSJS.summary <- paste("./summary/Tract_", toString(tract), '.0_HKY/sim_', 
                            toString(sim), '/PSJS_HKY_rv_sim_',
                            toString(sim), "_Tract_", toString(tract), '.0_guess_',
                            toString(guess),'.0_nt_summary.txt', sep = "")
      if (file.exists(PSJS.summary)){
        all <- readLines(PSJS.summary, n = -1)
        col.names <- paste("sim_", toString(sim), sep = "")
        row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
        summary_mat <- as.matrix(read.table(PSJS.summary, 
                                            row.names = row.names, 
                                            col.names = col.names))
        PSJS.tract.summary <- cbind(PSJS.tract.summary, summary_mat)
      }
    }
    assign(paste("PSJS_HKY_Tract_", toString(tract), "_guess_", 
                 toString(guess), "_summary", sep = ""), PSJS.tract.summary)
  }
}

# Now combine all initial guess results
for(tract in Tract.list){
  combined.PSJS.tract.summary <- NULL
  col.list <- NULL
  for ( sim_num in 1:100){
    sim_col <- paste("sim_", toString(sim_num), sep = "")
    best.lnL <- -Inf
    best.guess <- NULL
    for(guess in guess.list){
      target_summary <- get(paste("PSJS_HKY_Tract_", toString(tract), "_guess_", toString(guess), "_summary", sep = ""))
      if(sim_col %in% colnames(target_summary) ){
        if (target_summary["ll", sim_col] > best.lnL){
          best.lnL <- target_summary["ll", sim_col]
          best.guess <- guess        
        }
      }
    }
    if(! is.null(best.guess)){
      combined.PSJS.tract.summary <- cbind(combined.PSJS.tract.summary, 
                                           get(paste("PSJS_HKY_Tract_", toString(tract), "_guess_", toString(best.guess), "_summary", sep = ""))[, sim_col]) 
      col.list <- c(col.list, sim_col)
    }
    
  }
  colnames(combined.PSJS.tract.summary) <- col.list
  assign(paste("PSJS_HKY_Tract_", toString(tract), "_combined_summary", sep = ""), combined.PSJS.tract.summary)
}

# Now read in actual mean tract length in each simulated dataset
for (tract in Tract.list){
  sim.tract <- NULL
  for(sim in 1:100){
    sim_log <- paste("./Tract_", toString(tract), ".0_HKY/sim_", toString(sim), 
                     "/YDR418W_YEL054C_sim_", toString(sim), "_IGC.log", sep = "")
    # now read in log file
    log_info <- read.table(sim_log, header = TRUE)
    realized.tract.length <- log_info[, "stop_pos"] - log_info[, "start_pos"] + 1
    potential.tract.length <- log_info[, "tract_length"]
    # Now get longest length of variant subtract of each tract
    diff.tracts <- log_info[, "num_diff"] > 0
    if (sum(diff.tracts)){
      subtract.length.list <- NULL
      for(row.num in (1:dim(log_info)[1])[diff.tracts]){
        donor.seq <- strsplit(toString(log_info[row.num, "template_seq"]), "")[[1]]
        recipient.seq <- strsplit(toString(log_info[row.num, "overide_seq"]), "")[[1]]
        first.pos <- FALSE
        for(seq.pos in 1:length(donor.seq)){
          if(donor.seq[seq.pos] != recipient.seq[seq.pos]){
            last.pos <- seq.pos
            if(!first.pos){
              first.pos <- seq.pos
            }
          }
        }
        subtract.length.list <- c(subtract.length.list, last.pos - first.pos + 1)
      }
    }
    new.info <- matrix(c(dim(log_info)[1], mean(potential.tract.length), sd(potential.tract.length), 
                         mean(realized.tract.length), sd(realized.tract.length),
                         mean(potential.tract.length[diff.tracts]), 
                         mean(realized.tract.length[diff.tracts]),
                         mean(subtract.length.list),
                         sum(log_info[, "num_diff"] > 1)),
                       9, 1)
    rownames(new.info) <- c("num IGC", "mean potential tract length", "sd potential tract length", 
                            "mean realized tract length", "sd realized tract length", 
                            "mean potential nonidentical tract length", "mean realized nonidentical tract length",
                            "mean subtract length", "num IGC with at least two variant sites")
    colnames(new.info) <- paste("sim_", toString(sim), sep = "")
    sim.tract <- cbind(sim.tract, new.info)
  }
  assign(paste("sim.tract.", toString(tract), sep = ""), sim.tract)
}

```

Now plot the variance of lnL with varying log_p in each distance

```{r}
for (sim in 1:100){
  grid.lnL <- get(paste("Tract_", tract, ".0_sim_", sim, "_grid_lnL", sep = ""))
  sim.info <- get(paste("sim.tract.", tract, sep = ""))
  lnL.var <- apply(grid.lnL, 2, var)
  plot(lnL.var, type = "l", 
     xlab = "distance", ylab = "variance in lnL",
       main = sim)
  plot(exp(-grid.lnL[, 1]), rowSums(grid.lnL[, -1]), type = "b",
       xlab = "Tract length", ylab = "lnL", 
       main = paste("lnL vs Tract sim = ", sim))
  print(paste("In simulation, number of IGC events:", sim.info["num IGC", paste("sim", sim, sep = "_")], 
              ", mean potential tract length:", sim.info["mean potential tract length", paste("sim", sim, sep = "_")],
              ", mean realized tract length:", sim.info["mean realized tract length", paste("sim", sim, sep = "_")]))
  print(paste("Max lnL at grid value:", round(exp(-grid.lnL[, 1])[which.max(rowSums(grid.lnL[, -1]))])))
  if (paste("sim", sim, sep = "_") %in% colnames(PSJS_HKY_Tract_50_combined_summary)){
    print(paste("PSJS estimate:", PSJS_HKY_Tract_50_combined_summary["tract_length", paste("sim", sim, sep = "_")]))
    
  }
}
```

Save workspace

```{r}
save.image("./GridWeight.RData")
```
