#!/bin/bash
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_1_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_2_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_3_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_4_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_5_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_6_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_7_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_8_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_9_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_10_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_11_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_12_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_13_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_14_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_15_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_16_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_17_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_18_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_19_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_20_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_21_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_22_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_23_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_24_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_25_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_26_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_27_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_28_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_29_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_30_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_31_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_32_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_33_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_34_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_35_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_36_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_37_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_38_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_39_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_40_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_41_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_42_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_43_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_44_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_45_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_46_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_47_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_48_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_49_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_50_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_51_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_52_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_53_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_54_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_55_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_56_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_57_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_58_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_59_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_60_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_61_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_62_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_63_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_64_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_65_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_66_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_67_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_68_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_69_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_70_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_71_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_72_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_73_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_74_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_75_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_76_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_77_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_78_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_79_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_80_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_81_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_82_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_83_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_84_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_85_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_86_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_87_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_88_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_89_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_90_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_91_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_92_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_93_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_94_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_95_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_96_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_97_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_98_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_99_Tract_3.0.sh 
sbatch -o Half-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Half_100_Tract_3.0.sh 
