#!/bin/bash
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_1_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_2_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_3_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_4_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_5_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_6_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_7_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_8_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_9_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_10_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_11_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_12_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_13_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_14_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_15_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_16_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_17_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_18_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_19_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_20_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_21_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_22_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_23_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_24_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_25_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_26_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_27_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_28_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_29_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_30_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_31_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_32_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_33_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_34_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_35_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_36_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_37_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_38_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_39_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_40_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_41_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_42_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_43_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_44_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_45_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_46_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_47_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_48_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_49_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_50_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_51_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_52_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_53_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_54_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_55_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_56_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_57_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_58_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_59_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_60_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_61_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_62_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_63_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_64_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_65_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_66_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_67_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_68_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_69_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_70_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_71_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_72_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_73_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_74_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_75_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_76_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_77_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_78_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_79_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_80_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_81_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_82_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_83_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_84_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_85_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_86_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_87_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_88_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_89_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_90_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_91_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_92_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_93_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_94_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_95_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_96_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_97_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_98_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_99_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/HKY_100_Tract_100.0.sh 
