#!/bin/bash
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_1_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_2_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_3_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_4_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_5_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_6_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_7_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_8_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_9_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_10_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_11_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_12_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_13_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_14_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_15_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_16_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_17_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_18_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_19_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_20_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_21_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_22_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_23_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_24_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_25_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_26_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_27_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_28_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_29_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_30_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_31_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_32_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_33_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_34_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_35_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_36_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_37_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_38_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_39_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_40_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_41_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_42_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_43_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_44_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_45_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_46_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_47_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_48_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_49_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_50_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_51_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_52_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_53_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_54_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_55_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_56_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_57_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_58_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_59_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_60_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_61_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_62_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_63_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_64_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_65_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_66_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_67_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_68_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_69_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_70_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_71_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_72_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_73_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_74_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_75_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_76_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_77_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_78_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_79_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_80_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_81_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_82_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_83_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_84_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_85_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_86_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_87_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_88_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_89_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_90_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_91_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_92_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_93_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_94_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_95_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_96_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_97_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_98_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_99_Tract_100.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_100_Tract_100.0.sh 
