#!/bin/bash
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_1_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_2_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_3_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_4_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_5_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_6_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_7_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_8_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_9_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_10_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_11_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_12_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_13_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_14_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_15_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_16_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_17_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_18_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_19_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_20_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_21_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_22_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_23_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_24_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_25_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_26_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_27_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_28_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_29_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_30_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_31_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_32_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_33_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_34_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_35_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_36_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_37_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_38_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_39_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_40_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_41_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_42_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_43_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_44_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_45_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_46_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_47_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_48_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_49_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_50_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_51_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_52_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_53_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_54_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_55_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_56_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_57_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_58_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_59_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_60_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_61_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_62_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_63_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_64_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_65_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_66_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_67_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_68_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_69_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_70_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_71_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_72_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_73_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_74_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_75_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_76_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_77_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_78_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_79_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_80_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_81_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_82_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_83_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_84_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_85_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_86_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_87_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_88_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_89_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_90_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_91_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_92_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_93_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_94_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_95_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_96_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_97_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_98_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_99_Tract_200.0.sh 
sbatch -o HKY-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Old_100_Tract_200.0.sh 
