#!/bin/bash
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_1_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_2_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_3_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_4_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_5_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_6_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_7_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_8_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_9_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_10_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_11_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_12_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_13_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_14_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_15_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_16_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_17_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_18_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_19_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_20_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_21_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_22_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_23_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_24_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_25_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_26_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_27_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_28_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_29_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_30_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_31_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_32_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_33_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_34_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_35_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_36_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_37_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_38_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_39_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_40_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_41_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_42_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_43_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_44_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_45_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_46_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_47_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_48_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_49_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_50_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_51_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_52_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_53_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_54_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_55_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_56_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_57_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_58_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_59_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_60_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_61_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_62_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_63_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_64_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_65_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_66_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_67_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_68_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_69_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_70_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_71_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_72_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_73_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_74_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_75_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_76_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_77_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_78_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_79_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_80_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_81_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_82_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_83_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_84_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_85_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_86_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_87_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_88_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_89_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_90_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_91_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_92_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_93_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_94_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_95_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_96_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_97_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_98_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_99_Tract_50.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/PSJS_100_Tract_50.0.sh 
