#!/bin/bash
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_1_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_2_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_3_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_4_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_5_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_6_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_7_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_8_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_9_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_10_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_11_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_12_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_13_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_14_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_15_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_16_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_17_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_18_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_19_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_20_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_21_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_22_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_23_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_24_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_25_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_26_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_27_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_28_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_29_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_30_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_31_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_32_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_33_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_34_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_35_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_36_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_37_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_38_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_39_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_40_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_41_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_42_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_43_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_44_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_45_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_46_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_47_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_48_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_49_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_50_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_51_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_52_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_53_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_54_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_55_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_56_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_57_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_58_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_59_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_60_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_61_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_62_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_63_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_64_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_65_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_66_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_67_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_68_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_69_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_70_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_71_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_72_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_73_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_74_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_75_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_76_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_77_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_78_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_79_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_80_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_81_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_82_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_83_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_84_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_85_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_86_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_87_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_88_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_89_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_90_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_91_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_92_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_93_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_94_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_95_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_96_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_97_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_98_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_99_Tract_300.0.sh 
sbatch -o PSJS-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Sim_100_Tract_300.0.sh 
