#!/bin/bash
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_1_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_2_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_3_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_4_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_5_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_6_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_7_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_8_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_9_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_10_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_11_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_12_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_13_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_14_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_15_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_16_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_17_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_18_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_19_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_20_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_21_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_22_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_23_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_24_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_25_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_26_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_27_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_28_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_29_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_30_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_31_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_32_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_33_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_34_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_35_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_36_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_37_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_38_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_39_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_40_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_41_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_42_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_43_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_44_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_45_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_46_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_47_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_48_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_49_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_50_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_51_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_52_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_53_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_54_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_55_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_56_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_57_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_58_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_59_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_60_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_61_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_62_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_63_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_64_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_65_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_66_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_67_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_68_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_69_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_70_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_71_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_72_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_73_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_74_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_75_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_76_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_77_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_78_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_79_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_80_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_81_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_82_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_83_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_84_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_85_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_86_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_87_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_88_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_89_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_90_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_91_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_92_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_93_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_94_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_95_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_96_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_97_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_98_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_99_Tract_10.0.sh 
sbatch -o Tenth-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/Tenth_100_Tract_10.0.sh 
