#!/bin/bash
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_1_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_2_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_3_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_4_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_5_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_6_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_7_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_8_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_9_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_10_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_11_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_12_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_13_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_14_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_15_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_16_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_17_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_18_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_19_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_20_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_21_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_22_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_23_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_24_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_25_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_26_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_27_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_28_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_29_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_30_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_31_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_32_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_33_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_34_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_35_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_36_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_37_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_38_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_39_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_40_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_41_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_42_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_43_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_44_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_45_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_46_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_47_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_48_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_49_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_50_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_51_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_52_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_53_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_54_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_55_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_56_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_57_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_58_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_59_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_60_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_61_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_62_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_63_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_64_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_65_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_66_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_67_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_68_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_69_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_70_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_71_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_72_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_73_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_74_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_75_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_76_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_77_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_78_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_79_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_80_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_81_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_82_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_83_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_84_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_85_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_86_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_87_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_88_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_89_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_90_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_91_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_92_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_93_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_94_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_95_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_96_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_97_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_98_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_99_Tract_50.0.sh 
sbatch -o True-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./ShFiles/True_100_Tract_50.0.sh 
